// <auto-generated />
using System;
using KesarPremium.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KesarPremium.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KesarPremium.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("PlanId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Brochure", b =>
                {
                    b.Property<int>("BrochureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrochureId"));

                    b.Property<string>("BrochureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("BrochureId");

                    b.HasIndex("HostelId");

                    b.ToTable("Brochures");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Enquiry", b =>
                {
                    b.Property<int>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryId"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnquiryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HostelId")
                        .HasColumnType("int");

                    b.Property<int?>("HostelId1")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EnquiryId");

                    b.HasIndex("HostelId");

                    b.HasIndex("HostelId1");

                    b.HasIndex("UserId");

                    b.ToTable("Enquiries");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilityId = 1,
                            FacilityName = "Room Cleaning",
                            IconClass = "fas fa-broom",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 2,
                            FacilityName = "Toilet Cleaning",
                            IconClass = "fas fa-toilet",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 3,
                            FacilityName = "Electricity",
                            IconClass = "fas fa-bolt",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 4,
                            FacilityName = "Security",
                            IconClass = "fas fa-shield-alt",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 5,
                            FacilityName = "RO Water",
                            IconClass = "fas fa-tint",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 6,
                            FacilityName = "Vehicle Parking",
                            IconClass = "fas fa-parking",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 7,
                            FacilityName = "CCTV Cameras",
                            IconClass = "fas fa-video",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 8,
                            FacilityName = "WiFi",
                            IconClass = "fas fa-wifi",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 9,
                            FacilityName = "Breakfast",
                            IconClass = "fas fa-coffee",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 10,
                            FacilityName = "Lunch",
                            IconClass = "fas fa-utensils",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 11,
                            FacilityName = "Snacks",
                            IconClass = "fas fa-cookie",
                            IsActive = true
                        },
                        new
                        {
                            FacilityId = 12,
                            FacilityName = "Dinner",
                            IconClass = "fas fa-hamburger",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Hostel", b =>
                {
                    b.Property<int>("HostelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostelId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HostelId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.HostelCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("HostelCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Boys",
                            Description = "Hostel for male residents",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Girls",
                            Description = "Hostel for female residents",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Independent",
                            Description = "Private rooms for both",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.HostelFacility", b =>
                {
                    b.Property<int>("HostelFacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostelFacilityId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.HasKey("HostelFacilityId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("HostelId", "FacilityId")
                        .IsUnique();

                    b.ToTable("HostelFacilities");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.HostelImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("HostelId");

                    b.HasIndex("RoomId");

                    b.ToTable("HostelImages");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Address = "Vijay Nagar, Indore",
                            City = "Indore",
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3511),
                            IsActive = true,
                            LocationName = "Vijay Nagar",
                            PinCode = "452010",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            LocationId = 2,
                            Address = "Palasia, Indore",
                            City = "Indore",
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3514),
                            IsActive = true,
                            LocationName = "Palasia",
                            PinCode = "452001",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            LocationId = 3,
                            Address = "Bhawarkua, Indore",
                            City = "Indore",
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3516),
                            IsActive = true,
                            LocationName = "Bhawarkua",
                            PinCode = "452001",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            LocationId = 4,
                            Address = "Scheme 54, Indore",
                            City = "Indore",
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3517),
                            IsActive = true,
                            LocationName = "Scheme 54",
                            PinCode = "452010",
                            State = "Madhya Pradesh"
                        },
                        new
                        {
                            LocationId = 5,
                            Address = "AB Road, Indore",
                            City = "Indore",
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3517),
                            IsActive = true,
                            LocationName = "AB Road",
                            PinCode = "452008",
                            State = "Madhya Pradesh"
                        });
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGateway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.PricingPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<decimal>("BaseRent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.HasIndex("HostelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("PricingPlans");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3304),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 3, 2, 7, 47, 52, 458, DateTimeKind.Utc).AddTicks(3308),
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("AvailableBeds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.HasIndex("HostelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<int>("BedCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            BedCount = 1,
                            TypeName = "Single"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            BedCount = 2,
                            TypeName = "Double"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            BedCount = 3,
                            TypeName = "Triple"
                        },
                        new
                        {
                            RoomTypeId = 4,
                            BedCount = 6,
                            TypeName = "Dormitory"
                        });
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.SharedArea", b =>
                {
                    b.Property<int>("SharedAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SharedAreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SharedAreaId");

                    b.HasIndex("HostelId");

                    b.ToTable("SharedAreas");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.SharedAreaImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SharedAreaId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("SharedAreaId");

                    b.ToTable("SharedAreaImages");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Booking", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.PricingPlan", "Plan")
                        .WithMany("Bookings")
                        .HasForeignKey("PlanId");

                    b.HasOne("KesarPremium.Core.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Brochure", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany("Brochures")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Enquiry", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany()
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("KesarPremium.Core.Entities.Hostel", null)
                        .WithMany("Enquiries")
                        .HasForeignKey("HostelId1");

                    b.HasOne("KesarPremium.Core.Entities.User", "User")
                        .WithMany("Enquiries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hostel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Hostel", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.HostelCategory", "Category")
                        .WithMany("Hostels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.Location", "Location")
                        .WithMany("Hostels")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.HostelFacility", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Facility", "Facility")
                        .WithMany("HostelFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany("HostelFacilities")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.HostelImage", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany("Images")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId");

                    b.Navigation("Hostel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Notification", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Payment", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.User", null)
                        .WithMany("Payments")
                        .HasForeignKey("UserId1");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.PricingPlan", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany("PricingPlans")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.RoomType", "RoomType")
                        .WithMany("PricingPlans")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hostel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Room", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany("Rooms")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KesarPremium.Core.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hostel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.SharedArea", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Hostel", "Hostel")
                        .WithMany("SharedAreas")
                        .HasForeignKey("HostelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hostel");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.SharedAreaImage", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.SharedArea", "SharedArea")
                        .WithMany("Images")
                        .HasForeignKey("SharedAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedArea");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.User", b =>
                {
                    b.HasOne("KesarPremium.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Facility", b =>
                {
                    b.Navigation("HostelFacilities");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Hostel", b =>
                {
                    b.Navigation("Brochures");

                    b.Navigation("Enquiries");

                    b.Navigation("HostelFacilities");

                    b.Navigation("Images");

                    b.Navigation("PricingPlans");

                    b.Navigation("Rooms");

                    b.Navigation("SharedAreas");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.HostelCategory", b =>
                {
                    b.Navigation("Hostels");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Location", b =>
                {
                    b.Navigation("Hostels");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.PricingPlan", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.RoomType", b =>
                {
                    b.Navigation("PricingPlans");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.SharedArea", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("KesarPremium.Core.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Enquiries");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
